/*
 * Created on 2022-11-27 ( 18:26:59 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.hider.eee_students_login;

import java.io.Serializable;
import java.util.Arrays;

import jakarta.persistence.*;
//import javax.persistence.*;

/**
 * JPA entity class for "Filemodel"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="filemodel", schema="public" )
public class Filemodel implements Serializable {

   

	private static final long serialVersionUID = 1L;

    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="id", nullable=false)
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Integer    id ;

    //--- ENTITY DATA FIELDS 
    @Column(name="name", length=50)
    private String     name ;

    @Column(name="filetype", length=50)
    private String     filetype ;

    @Column(name="content")
    private byte[]       content ;

    
    

    //--- ENTITY LINKS ( RELATIONSHIP )

    /**
     * Constructor
     */
    public Filemodel() {
		
    }
    
    
    public Filemodel(String name, String filetype, byte[] content) {
		this.name = name;
		this.filetype = filetype;
		this.content = content;
	}
    //--- GETTERS & SETTERS FOR FIELDS
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    public void setName( String name ) {
        this.name = name ;
    }
    public String getName() {
        return this.name;
    }

    public void setFiletype( String filetype ) {
        this.filetype = filetype ;
    }
    public String getFiletype() {
        return this.filetype;
    }

    public void setContent( byte[] content ) {
        this.content = content ;
    }
    public byte[] getContent() {
        return this.content;
    }


	@Override
	public String toString() {
		return "Filemodel [id=" + id + ", name=" + name + ", filetype=" + filetype + ", content="
				+ Arrays.toString(content) + "]";
	}

    //--- GETTERS FOR LINKS
    //--- toString specific method
//	@Override
//    public String toString() { 
//        StringBuilder sb = new StringBuilder(); 
//        sb.append(id);
//        sb.append("|");
//        sb.append(name);
//        sb.append("|");
//        sb.append(filetype);
//        sb.append("|");
//        sb.append(content);
//        return sb.toString(); 
//    } 
    

}
